"""Generate Python binding property tables from sim_data JSON files.

Produces two outputs:
  - C++ header with get_{group}_table() functions for bind_sim_data.cpp
  - Python module with {GROUP}_KEYS lists for simucube_api/_sim_data.py
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib

PROPERTY_TYPES = {
    "bool",
    "f32",
    "f64",
    "i64",
    "i32",
    "i8",
    "string",
    "enum",
}

PROPERTY_TYPE_SORT_ORDER = {
    "bool": 6,
    "f32": 3,
    "f64": 1,
    "i64": 0,
    "i32": 2,
    "i8": 4,
    "string": 7,
    "enum": 5,
}

# Maps JSON group name -> (SubSection, Builder, namespace, Python var name)
GROUP_META = {
    "vehicle": ("Vehicle", "VehicleBuilder", "vehicle", "VEHICLE_KEYS"),
    "track": ("Track", "TrackBuilder", "track", "TRACK_KEYS"),
    "participant": ("Participant", "ParticipantBuilder", "participant", "PARTICIPANT_KEYS"),
    "session": ("Session", "SessionBuilder", "session", "SIM_SESSION_KEYS"),
    "tire": ("Tire", "TireBuilder", "tire", "TIRE_KEYS"),
    "sim": ("Sim", "SimBuilder", "sim", "SIM_KEYS"),
}

GROUPS_ORDERED = ["vehicle", "track", "participant", "session", "tire", "sim"]


def parse_properties(json_path: pathlib.Path) -> list[str]:
    """Parse a properties JSON and return property names sorted by type sort order."""
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    props = []
    for name, info in data.items():
        ptype = info["type"]
        if ptype not in PROPERTY_TYPES:
            continue
        props.append((name, ptype))

    props.sort(key=lambda p: PROPERTY_TYPE_SORT_ORDER[p[1]])
    return [name for name, _ in props]


def generate_cpp(groups: dict[str, list[str]]) -> str:
    """Generate C++ header content with get_{group}_table() functions."""
    lines = ["// Auto-generated by generate_python_binding_tables.py — do not edit.", ""]

    for group in GROUPS_ORDERED:
        subsection, builder, namespace, _ = GROUP_META[group]
        entry_type = f"{subsection}Entry"
        names = groups[group]

        lines.append(f"static const std::vector<{entry_type}>& get_{group}_table() {{")
        lines.append(f"    static const std::vector<{entry_type}> t = {{")
        for name in names:
            lines.append(f"        make_entry<{subsection}, {builder}>({namespace}::{name}),")
        lines.append("    };")
        lines.append("    return t;")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def generate_py(groups: dict[str, list[str]]) -> str:
    """Generate Python module content with key lists."""
    lines = ['"""Auto-generated by generate_python_binding_tables.py — do not edit."""', ""]

    for group in GROUPS_ORDERED:
        _, _, _, py_var = GROUP_META[group]
        names = groups[group]

        lines.append(f"{py_var} = [")
        for name in names:
            lines.append(f'    "{name}",')
        lines.append("]")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(prog="generate_python_binding_tables")
    parser.add_argument("--data-dir", required=True, type=pathlib.Path,
                        help="Directory containing {group}_properties.json files")
    parser.add_argument("--cpp-output", required=True, type=pathlib.Path,
                        help="Output path for C++ header")
    parser.add_argument("--py-output", required=True, type=pathlib.Path,
                        help="Output path for Python module")
    args = parser.parse_args()

    groups: dict[str, list[str]] = {}
    for group in GROUPS_ORDERED:
        json_path = args.data_dir / f"{group}_properties.json"
        groups[group] = parse_properties(json_path)

    cpp_content = generate_cpp(groups)
    os.makedirs(args.cpp_output.parent, exist_ok=True)
    with open(args.cpp_output, "w", encoding="utf-8") as f:
        f.write(cpp_content)

    py_content = generate_py(groups)
    os.makedirs(args.py_output.parent, exist_ok=True)
    with open(args.py_output, "w", encoding="utf-8") as f:
        f.write(py_content)

    total = sum(len(v) for v in groups.values())
    print(f"Generated {total} property entries across {len(groups)} groups")


if __name__ == "__main__":
    main()
