"""Generate nanobind enum binding code from device_info_enums.json.

Produces a C++ header with nb::enum_<> declarations and .value() calls
for each device_info enum, including per-value docstrings from the JSON data.
"""

import argparse
import json
import os
import pathlib
import sys


def generate_binding(enum_def):
    """Generate nanobind binding code for a single enum definition."""
    lines = []
    name = enum_def["name"]
    py_desc = enum_def["python_description"]

    lines.append(f'nb::enum_<device_info::{name}>(m, "{name}",')
    lines.append(f'                               "{py_desc}")')

    for val in enum_def["values"]:
        desc = val.get("description")
        if desc:
            # Escape any quotes in description
            desc = desc.replace('"', '\\"')
            lines.append(f'    .value("{val["name"]}", device_info::{name}::{val["name"]}, "{desc}")')
        else:
            lines.append(f'    .value("{val["name"]}", device_info::{name}::{val["name"]})')

    lines.append("    ;")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(prog="generate_device_info_bindings")
    parser.add_argument("enums_json", type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    with open(args.enums_json, encoding="UTF-8") as f:
        data = json.load(f)

    blocks = []
    for enum_def in data["enums"]:
        blocks.append(generate_binding(enum_def))

    content = "// Auto-generated by generate_device_info_bindings.py — do not edit.\n\n"
    content += "\n\n".join(blocks) + "\n"

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", newline="\n") as f:
        f.write(content)

    print(f"Generated nanobind bindings for {len(data['enums'])} device_info enums -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
